# Requirements
sudo: required
# Docker service required
services:
  - docker

language: java

# Travis env specified
os: linux
dist: trusty
jdk: openjdk8

# Permission to run gradlew script
before_install:
  - chmod +x gradlew

# Run tests
script:
  - ./gradlew test
# Deploy on docker hub
after_success:
  - ./gradlew build
  - sh ./deploy_dockerhub.sh